target: write 
auth_enabled: false

common:
  replication_factor: 1 
  ring:
    kvstore:
      store: inmemory
  storage:
    s3:
      s3: http://minioadmin:minioadmin@172.20.0.2:9000
      bucketnames: loki
      insecure: true
      s3forcepathstyle: true
      #region: piano-loki

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 1m #default 10m
  retention_enabled: true #Without this, the Compactor will only compact tables.
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  max_compaction_parallelism: 10 #default 1 maximum number of tables to compact in parallel
  delete_request_cancel_period: 24h #default 24h Data would be deleted only after delete requests have been older than this duration.

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9098
  log_level: info

ingester:
  max_transfer_retries: 0
  chunk_encoding: snappy
  chunk_idle_period: 2h
  chunk_target_size: 1572864 
  max_chunk_age: 4h
  wal:
    dir: /loki/wal
#  lifecycler:
#    interface_names:
#      - enp35s0

schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  index_queries_cache_config:
    enable_fifocache: true
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache

limits_config:
  retention_period: 240h 
  retention_stream:
  - selector: '{app="haproxy"}'
    priority: 1
    period: 24h
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h #default 168h
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 20
  max_query_parallelism: 2
  max_global_streams_per_user: 20000 #default 5000
  per_stream_rate_limit: 30MB #default 3MB
  per_stream_rate_limit_burst: 30MB #default 15MB. This is how far above the rate limit a stream can "burst" before the stream is limited.

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 20GB
